version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ash@123
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data:
